FROM node:6-alpine

RUN apk add --no-cache make gcc g++ python bash libc6-compat

RUN mkdir /src
WORKDIR /src

ADD nodemon.json /src/nodemon.json

ADD deploy/wait-for-it.sh /wait-for-it.sh
RUN chmod a+x /wait-for-it.sh

ADD package.json /src/package.json
RUN npm install

CMD npm run dev