---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: acaleph
  namespace: platform-fastpay
  labels:
    app: acaleph
    repo: manyu-ops
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: acaleph
      repo: manyu-ops
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: acaleph
        repo: manyu-ops
    spec:
      imagePullSecrets:
        - name: docker-reg
      containers:
        - name: acaleph
          image: registry-vpc.cn-hangzhou.aliyuncs.com/zft-energy/acaleph:a${BUILD_NUMBER}
          envFrom:
            - configMapRef:
                 name: acaleph-env
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: RDS_WRITE
              valueFrom:
                secretKeyRef:
                  name: fastpay-secret
                  key: RDS_WRITE
            - name: RDS_READ
              valueFrom:
                secretKeyRef:
                  name: fastpay-secret
                  key: RDS_READ
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: fastpay-secret
                  key: MONGODB_URL

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: acaleph
    repo: manyu-ops
  name: acaleph-env
  namespace: platform-fastpay
data:
  TZ: Asia/Shanghai
  MQ_HOST: redis.platform-fastpay
  MQ_PORT: '6379'
  MQ_PASS: ""
  ENV: production
  RPC_IP: columba.platform-fastpay
  APP_ID: ""
  APP_SECRET: ""
